(function(){
 const A=()=>window.VETOR;
 const $=s=>document.querySelector(s);
 function safe(s){return A()?.safe?A().safe(s??''):String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));}
 function norm(s){return String(s||'').trim();}
 function desc(x){let s=norm(x).toUpperCase(); if(!s)return ''; s=s.replace(/^DESCRITOR\s*/,'').replace(/^D\s*/,'D'); if(/^\d+$/.test(s))s='D'+s; return s;}
 function uid(){return 'INT'+Date.now().toString(36)+Math.random().toString(36).slice(2,7).toUpperCase();}
 function download(name, content, type='text/plain;charset=utf-8'){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},400);}
 const DEFAULTS=[
  ['Língua Portuguesa','D1','Leitura guiada com localização de informações explícitas','Selecionar textos curtos, pedir que os estudantes grifem informações solicitadas e justifiquem onde encontraram a resposta.','Fácil','15 min'],
  ['Língua Portuguesa','D3','Vocabulário em contexto','Apresentar palavras retiradas de textos reais e solicitar que os alunos infiram o sentido pelo contexto antes de consultar o dicionário.','Média','20 min'],
  ['Língua Portuguesa','D4','Inferência por pistas textuais','Trabalhar tirinhas, notícias curtas e crônicas. Solicitar que os estudantes apontem pistas que sustentam cada inferência.','Média','25 min'],
  ['Língua Portuguesa','D6','Identificação de tema central','Ler textos de diferentes gêneros e pedir que os alunos formulem o tema em uma frase curta, separando assunto amplo e ideia central.','Fácil','20 min'],
  ['Língua Portuguesa','D11','Fato e opinião','Comparar trechos informativos e opinativos, destacando marcas linguísticas de avaliação, julgamento e subjetividade.','Média','25 min'],
  ['Língua Portuguesa','D14','Causa e consequência','Montar quadros com acontecimentos do texto e pedir que os alunos indiquem relações de causa e efeito explicitadas ou inferidas.','Média','25 min'],
  ['Língua Portuguesa','D15','Conectivos e relações lógico-discursivas','Criar cartões com conectivos e pedir que os estudantes classifiquem a relação indicada: oposição, conclusão, explicação, adição ou tempo.','Média','20 min'],
  ['Língua Portuguesa','D20','Finalidade do texto','Apresentar gêneros variados e discutir para que cada texto foi produzido, quem fala, para quem fala e com qual intenção.','Fácil','20 min'],
  ['Matemática','D1','Retomada de leitura de gráfico e tabela','Analisar gráficos simples da rotina escolar e pedir que os estudantes localizem informações antes de realizar cálculos.','Fácil','20 min'],
  ['Matemática','D2','Problemas graduados por estratégia','Resolver problemas em três etapas: compreender o enunciado, escolher operação e conferir a plausibilidade da resposta.','Média','30 min'],
  ['Matemática','D10','Revisão com exemplos resolvidos','Apresentar um exemplo modelo, resolver coletivamente e depois propor variações com números diferentes.','Fácil','25 min'],
  ['Matemática','D15','Oficina de erro comum','Selecionar respostas incorretas frequentes e discutir por que parecem plausíveis e onde o raciocínio falhou.','Média','25 min']
 ].map(([discipline,descriptor,title,description,difficulty,time])=>({id:uid(),builtin:true,discipline,descriptor,title,description,difficulty,time,type:'Atividade de recomposição',resource:'',source:'Banco interno'}));
 function store(){const st=A()?.state; if(!st)return []; st.interventions=st.interventions||[]; return st.interventions;}
 function all(){return [...DEFAULTS,...store()];}
 function byDescriptor(disc, code){code=desc(code); return all().filter(i=>(!disc||i.discipline===disc||i.discipline==='Todas') && desc(i.descriptor)===code);}
 function descriptorInfo(disc, code){return (window.Descritores?.list(disc)||[]).find(x=>x.codigo===code) || {texto:'Descritor priorizado para recomposição da aprendizagem.'};}
 function suggestText(priorities=[],disc='Língua Portuguesa',limit=3){
   const ps=(priorities||[]).map(p=>typeof p==='string'?{descriptor:p}:p).slice(0,limit);
   if(!ps.length)return 'Manter rotina de aprofundamento com itens variados, correção comentada e acompanhamento do desempenho.';
   return ps.map(p=>{const code=desc(p.descriptor||p.descritor); const info=descriptorInfo(disc,code); const opts=byDescriptor(disc,code); const chosen=opts.length?opts[Math.floor(Math.random()*opts.length)]:null; return `${code}: ${chosen?chosen.description:('retomar '+info.texto+' com leitura guiada, exemplos resolvidos, exercícios graduados e devolutiva comentada.')}`;}).join(' ');
 }
 function priorityClass(){const r=A()?.getResults?.(); return (r?.descriptorStats||[]).slice().sort((a,b)=>a.percent-b.percent).slice(0,4).map(d=>({descriptor:d.descritor,percent:d.percent,errors:Math.max(1,100-d.percent)}));}
 function priorityStudent(idx){return window.BancoQuestoes?.priorityDescriptors?window.BancoQuestoes.priorityDescriptors(idx):[];}
 function fillForm(item={}){[['#intDisc',item.discipline||'Língua Portuguesa'],['#intDesc',item.descriptor||''],['#intTitle',item.title||''],['#intType',item.type||'Atividade de recomposição'],['#intDiff',item.difficulty||'Média'],['#intTime',item.time||'20 min'],['#intResource',item.resource||''],['#intSource',item.source||'Autoral'],['#intText',item.description||'']].forEach(([s,v])=>{const e=$(s); if(e)e.value=v;});}
 function add(){const q={id:uid(),discipline:$('#intDisc')?.value||'Língua Portuguesa',descriptor:desc($('#intDesc')?.value||''),title:norm($('#intTitle')?.value),type:$('#intType')?.value||'Atividade de recomposição',difficulty:$('#intDiff')?.value||'Média',time:norm($('#intTime')?.value),resource:norm($('#intResource')?.value),source:norm($('#intSource')?.value)||'Autoral',description:norm($('#intText')?.value)}; if(!q.descriptor||!q.title||!q.description){alert('Informe descritor, título e descrição da intervenção.');return;} store().push(q); A()?.save?.(); fillForm(); render();}
 function filtered(){const disc=$('#intFilterDisc')?.value||''; const d=desc($('#intFilterDesc')?.value||''); const term=norm($('#intSearch')?.value).toLowerCase(); return all().filter(i=>(!disc||i.discipline===disc)&&(!d||desc(i.descriptor)===d)&&(!term||JSON.stringify(i).toLowerCase().includes(term)));}
 function renderList(){const box=$('#interventionList'); if(!box)return; const data=filtered(); box.innerHTML=data.map((i,k)=>`<div class="bankItem intervention-item"><header><div><b>${safe(i.title)}</b><div class="meta"><span>${safe(i.discipline)}</span><span>${safe(i.descriptor)}</span><span>${safe(i.type)}</span><span>${safe(i.difficulty)}</span><span>${safe(i.time||'-')}</span><span>${i.builtin?'interno':'próprio'}</span></div></div><div>${i.builtin?'':`<button class="smallBtn secondary" data-edit-int="${k}">Editar</button> <button class="smallBtn danger" data-del-int="${k}">Excluir</button>`}</div></header><p>${safe(i.description)}</p>${i.resource?`<p class="hint"><b>Recurso:</b> ${safe(i.resource)}</p>`:''}</div>`).join('')||'<p class="hint">Nenhuma intervenção encontrada.</p>';
  box.querySelectorAll('[data-del-int]').forEach(b=>b.onclick=()=>{const item=data[Number(b.dataset.delInt)]; const idx=store().findIndex(x=>x.id===item.id); if(idx>=0&&confirm('Excluir intervenção?')){store().splice(idx,1);A()?.save?.();render();}});
  box.querySelectorAll('[data-edit-int]').forEach(b=>b.onclick=()=>{const item=data[Number(b.dataset.editInt)]; const idx=store().findIndex(x=>x.id===item.id); if(idx>=0){fillForm(item); store().splice(idx,1); A()?.save?.(); render(); window.scrollTo({top:0,behavior:'smooth'});}});
 }
 function renderSuggestions(){const out=$('#interventionSuggestions'); if(!out)return; const disc=$('#intSuggestDisc')?.value||A()?.state?.assessment?.discipline||'Língua Portuguesa'; const mode=$('#intSuggestMode')?.value||'turma'; const idx=Number($('#intSuggestStudent')?.value||-1); let pr=mode==='aluno'?priorityStudent(idx):priorityClass(); const manual=($('#intSuggestManual')?.value||'').split(/[,;\s]+/).filter(Boolean).map(x=>({descriptor:desc(x)})); if(manual.length)pr=manual; if(!pr.length){out.innerHTML='<p class="hint">Importe uma avaliação ou informe descritores manualmente.</p>';return;} out.innerHTML=`<div class="statusbox status-ok"><b>IA pedagógica V68.7.1</b><br>As recomendações abaixo vêm do banco pedagógico de intervenções, sem API paga.</div>`+pr.slice(0,5).map(p=>{const code=desc(p.descriptor||p.descritor); const info=descriptorInfo(disc,code); const opts=byDescriptor(disc,code); return `<div class="panel-mini"><h4>${safe(code)} — ${safe(info.texto)}</h4><p class="hint">${p.percent!==undefined?`Desempenho da turma: ${p.percent}%`:'Descritor priorizado'}</p>${opts.slice(0,4).map(i=>`<div class="intervention-suggestion"><b>${safe(i.title)}</b><p>${safe(i.description)}</p><small>${safe(i.type)} • ${safe(i.difficulty)} • ${safe(i.time||'-')}</small></div>`).join('')||`<p>Retomar o descritor com exercícios graduados, correção comentada e monitoramento na próxima avaliação.</p>`}</div>`;}).join('');}
 function exportJson(){download('banco-intervencoes-v58.json',JSON.stringify(store(),null,2),'application/json');}
 function exportCsv(){const rows=[['Disciplina','Descritor','Titulo','Tipo','Nivel','Tempo','Recurso','Fonte','Descricao'],...store().map(i=>[i.discipline,i.descriptor,i.title,i.type,i.difficulty,i.time,i.resource,i.source,i.description])]; download('banco-intervencoes-v58.csv',rows.map(r=>r.map(v=>'"'+String(v||'').replace(/"/g,'""')+'"').join(';')).join('\n'),'text/csv;charset=utf-8');}
 function parseCSV(txt){const sep=txt.includes(';')?';':','; const lines=txt.split(/\r?\n/).filter(Boolean); const head=lines.shift().split(sep).map(x=>x.replace(/^"|"$/g,'').trim()); return lines.map(line=>{const vals=line.split(sep).map(x=>x.replace(/^"|"$/g,'').trim()); const o={}; head.forEach((h,i)=>o[h]=vals[i]||''); return o;});}
 async function importFile(e){const f=e.target.files?.[0]; if(!f)return; try{let arr=[]; if(/\.json$/i.test(f.name)){const data=JSON.parse(await f.text()); arr=Array.isArray(data)?data:(data.intervencoes||data.interventions||[]);} else {arr=parseCSV(await f.text());} const mapped=arr.map(o=>({id:uid(),discipline:o.Disciplina||o.discipline||'Língua Portuguesa',descriptor:desc(o.Descritor||o.descriptor),title:o.Titulo||o.Título||o.title,type:o.Tipo||o.type||'Atividade de recomposição',difficulty:o.Nivel||o.Nível||o.difficulty||'Média',time:o.Tempo||o.time||'',resource:o.Recurso||o.resource||'',source:o.Fonte||o.source||'Importado',description:o.Descricao||o.Descrição||o.description})).filter(x=>x.descriptor&&x.title&&x.description); if(!mapped.length)throw new Error('Nenhuma intervenção válida encontrada.'); store().push(...mapped); A()?.save?.(); const st=$('#intImportStatus'); if(st)st.textContent=`Importadas ${mapped.length} intervenção(ões).`; render();}catch(err){alert('Erro ao importar intervenções: '+err.message);} e.target.value='';}
 function populateStudents(){const sel=$('#intSuggestStudent'); if(!sel)return; const students=A()?.state?.assessment?.students||[]; const cur=sel.value; sel.innerHTML='<option value="">Selecione</option>'+students.map((s,i)=>`<option value="${i}">${safe(s.name)}</option>`).join(''); sel.value=cur;}
 function render(){const stat=$('#interventionStats'); if(stat){const total=all().length, own=store().length; const by={}; all().forEach(i=>by[i.discipline]=(by[i.discipline]||0)+1); stat.innerHTML=`<span class="pill"><b>${total}</b> intervenções</span><span class="pill"><b>${own}</b> próprias/importadas</span>`+Object.entries(by).map(([k,v])=>`<span class="pill">${safe(k)}: ${v}</span>`).join('');} populateStudents(); renderList(); renderSuggestions();}
 function bind(){['#intFilterDisc','#intFilterDesc','#intSearch'].forEach(s=>$(s)&&($(s).oninput=$(s).onchange=renderList)); ['#intSuggestDisc','#intSuggestMode','#intSuggestStudent','#intSuggestManual'].forEach(s=>$(s)&&($(s).oninput=$(s).onchange=renderSuggestions)); $('#addIntervention')&&($('#addIntervention').onclick=add); $('#clearInterventionForm')&&($('#clearInterventionForm').onclick=()=>fillForm()); $('#exportInterventions')&&($('#exportInterventions').onclick=exportJson); $('#exportInterventionsCsv')&&($('#exportInterventionsCsv').onclick=exportCsv); $('#importInterventions')&&($('#importInterventions').onchange=importFile); $('#downloadInterventionTemplate')&&($('#downloadInterventionTemplate').onclick=()=>download('modelo-intervencoes.csv','Disciplina;Descritor;Titulo;Tipo;Nivel;Tempo;Recurso;Fonte;Descricao\nLíngua Portuguesa;D4;Inferência com tirinhas;Atividade de recomposição;Média;25 min;;Autoral;Trabalhar inferência com tirinhas e pedir que os alunos justifiquem as pistas usadas.','text/csv;charset=utf-8'));}
 document.addEventListener('DOMContentLoaded',bind);
 window.Intervencoes={render,all,store,byDescriptor,suggestText,priorityClass,priorityStudent};
})();
