(function(){
 const A=()=>window.VETOR;
 function weakByStudent(s){const m={};s.correct.forEach((c,i)=>{if(!c){const d=A().state.assessment.descriptors[i]||'Sem descritor';m[d]=(m[d]||0)+1;}});return Object.entries(m).sort((a,b)=>b[1]-a[1]);}
 function baseHeader(title){const a=A().state.assessment;return `${title}\nVETOR\nTurma: ${a.turma||'não informada'}\nDisciplina: ${a.discipline}\nAvaliação: ${a.title||'Avaliação atual'}\nData: ${a.date||'não informada'}\n\n`;}
 function levelCounts(r){return Object.entries(r.summary.levels||{}).map(([k,v])=>`- ${k}: ${v}`).join('\n');}
 function turma(){const r=A().getResults();return baseHeader('RELATÓRIO DA TURMA')+`Alunos avaliados: ${r.summary.nStudents}\nQuestões: ${r.summary.nQuestions}\nMédia geral: ${r.summary.avg}\nAlunos em Elementar I/II: ${r.summary.priority}\n\nClassificação pedagógica estimada:\n${levelCounts(r)}\n\nObservação técnica:\nA classificação Elementar I, Elementar II, Básico e Desejável é uma leitura pedagógica interna baseada no percentual de acertos desta avaliação. É uma leitura pedagógica interna baseada no percentual de acertos desta avaliação.\n\nDescritores críticos:\n`+r.descriptorStats.slice(0,10).map(d=>`- ${d.descritor}: ${d.percent}% (${d.students.length} aluno(s) com dificuldade)`).join('\n')+`\n\nQuestões com menor desempenho:\n`+[...r.items].sort((a,b)=>a.percent-b.percent).slice(0,8).map(it=>`- ${it.question} (${it.descriptor}): ${it.percent}%`).join('\n')+`\n\nEncaminhamento coletivo:\nPriorizar os três descritores de menor aproveitamento, iniciar com correção comentada, depois atividade guiada e nova verificação curta.`;}
 function familia(){const r=A().getResults();return baseHeader('RELATÓRIO PARA FAMÍLIA')+r.students.map(s=>{const w=weakByStudent(s).slice(0,3).map(x=>x[0]).join(', ')||'sem dificuldade prioritária';return `${s.name}\nDesempenho: ${s.percent}% — ${s.level}.\nLeitura pedagógica: ${s.levelDescription}\nPontos que precisam de atenção: ${w}.\nOrientação: manter rotina semanal de estudo, revisar os conteúdos indicados e realizar exercícios curtos com correção.`;}).join('\n\n');}
 function conselho(){const r=A().getResults();return baseHeader('RELATÓRIO PARA CONSELHO DE CLASSE')+`Panorama: média ${r.summary.avg}, ${r.summary.priority} aluno(s) em Elementar I/II.\n\nDistribuição por nível:\n${levelCounts(r)}\n\nAlunos em Elementar I e Elementar II:\n`+r.students.filter(s=>s.level==='Elementar I'||s.level==='Elementar II').map(s=>`- ${s.name}: ${s.percent}% • ${s.level} | descritores: ${weakByStudent(s).slice(0,3).map(x=>x[0]).join(', ')}`).join('\n')+`\n\nIntervenção sugerida:\nOrganizar grupos por descritores críticos, aplicar recuperação paralela de 4 semanas e acompanhar evolução em novo simulado.`;}
 function coordenacao(){const r=A().getResults();const crit=r.descriptorStats.slice(0,8);const prior=r.students.filter(s=>s.level==='Elementar I'||s.level==='Elementar II');return baseHeader('RELATÓRIO DA COORDENAÇÃO')+`Indicadores gerais: ${r.summary.nStudents} alunos, média ${r.summary.avg}, ${r.descriptorStats.filter(d=>d.percent<40).length} descritores críticos.\n\nDistribuição por nível pedagógico:\n${levelCounts(r)}\n\nDescritores críticos da escola/turma:\n`+crit.map((d,i)=>`${i+1}. ${d.descritor} — ${d.percent}% — ${d.students.length} aluno(s)`).join('\n')+`\n\nAlunos prioritários:\n`+prior.slice(0,30).map(s=>`- ${s.name}: ${s.percent}% • ${s.level}`).join('\n')+`\n\nAções recomendadas para a coordenação:\n1. Organizar intervenção por grupos de descritores, não apenas por nota final.\n2. Destinar acompanhamento imediato aos alunos em Elementar I e Elementar II.\n3. Solicitar aos professores uma devolutiva comentada das questões de menor acerto.\n4. Planejar nova verificação em 4 semanas com os mesmos descritores prioritários.\n5. Comparar Português e Matemática por turma para identificar assimetrias entre áreas.\n6. Registrar evidências: ficha aplicada, frequência na intervenção e evolução por aluno.\n\nEvolução geral registrada:\n`+(A().state.snapshots||[]).map(s=>`- ${s.name}: média ${s.avg}% (${s.date})`).join('\n');}
 function individual(idx=0){const r=A().getResults();const s=r.students[idx]||r.students[0];if(!s)return baseHeader('RELATÓRIO INDIVIDUAL')+'Nenhum aluno carregado.';const weak=weakByStudent(s);return baseHeader('RELATÓRIO INDIVIDUAL')+`Aluno: ${s.name}
Desempenho: ${s.total}/${r.summary.nQuestions} (${s.percent}%)
Classificação pedagógica estimada: ${s.level}
Leitura: ${s.levelDescription}

Descritores prioritários:\n`+weak.map(([d,n])=>`- ${d}: ${n} erro(s)`).join('\n')+`\n\nPlano imediato:\n1. Retomar os descritores com mais erros.\n2. Resolver exemplos guiados.\n3. Aplicar lista individualizada.\n4. Conferir evolução na próxima avaliação.`;}
 function build(type){if(type==='familia')return familia(); if(type==='conselho')return conselho(); if(type==='coordenacao')return coordenacao(); if(type==='individual'){const idx=Number(A().$('#reportStudent')?.value||0);return individual(idx);} return turma();}
 function compareDisciplines(){const snaps=A().state.snapshots||[];const groups={};snaps.forEach(s=>{const turma=s.turma||'Turma não informada'; const disc=s.discipline||'Disciplina não informada'; (groups[turma]??={}); (groups[turma][disc]??=[]).push(Number(s.avg)||0);});return Object.entries(groups).map(([turma,byDisc])=>{const lp=byDisc['Língua Portuguesa']||[]; const mat=byDisc['Matemática']||[]; const avg=arr=>arr.length?Math.round(arr.reduce((a,b)=>a+b,0)/arr.length*10)/10:null; return {turma,lp:avg(lp),mat:avg(mat),nLP:lp.length,nMat:mat.length,diff:(avg(lp)!=null&&avg(mat)!=null)?Math.round((avg(lp)-avg(mat))*10)/10:null};});}
 function renderComparison(){const box=A().$('#disciplineComparison'); if(!box)return; const rows=compareDisciplines();if(!rows.length){box.innerHTML='<h3>Comparação Português × Matemática</h3><p class="hint">Salve avaliações no histórico para comparar as disciplinas por turma. Exemplo: Diagnóstica de Português e Diagnóstica de Matemática da mesma turma.</p>';return;}box.innerHTML='<h3>Comparação Português × Matemática</h3><p class="hint">A comparação usa avaliações salvas no histórico local.</p><div class="preview-table"><div class="preview-row"><span>Turma</span><span>Português</span><span>Matemática</span><span>Diferença LP-MAT</span><span>Registros LP</span><span>Registros MAT</span></div>'+rows.map(r=>`<div class="preview-row"><span><b>${A().safe(r.turma)}</b></span><span>${r.lp==null?'-':r.lp+'%'}</span><span>${r.mat==null?'-':r.mat+'%'}</span><span>${r.diff==null?'-':r.diff+' p.p.'}</span><span>${r.nLP}</span><span>${r.nMat}</span></div>`).join('')+'</div>';}
 function actionPlan(r){
  const crit=r.descriptorStats.slice(0,3); const prior=r.students.filter(s=>s.level==='Elementar I'||s.level==='Elementar II');
  return `<div class="panel action-coord"><h3>Plano de ação sugerido para a coordenação</h3><ol><li><b>Semana 1 — devolutiva orientada:</b> promover correção comentada das questões ligadas a ${crit.map(d=>A().safe(d.descritor)).join(', ')||'descritores críticos'}.</li><li><b>Semana 2 — agrupamento:</b> organizar grupos de intervenção pelos descritores, priorizando ${prior.length} aluno(s) em Elementar I/II.</li><li><b>Semana 3 — prática monitorada:</b> aplicar ficha curta com 10 itens por aluno, registrando presença e progresso.</li><li><b>Semana 4 — reavaliação:</b> reaplicar itens dos descritores críticos e comparar evolução por turma e disciplina.</li></ol><p class="hint">A coordenação deve evitar usar apenas a média geral: a ação mais eficiente é por descritor e por grupo de necessidade.</p></div>`;
 }

 function assessmentName(a){
  const tipoMap={diagnostica:'Diagnóstica',simulado1:'Simulado 1',simulado2:'Simulado 2',recuperacao:'Recuperação',bimestral:'Bimestral'};
  return `${a.turma||'Turma não informada'} • ${a.discipline||'Disciplina não informada'} • ${tipoMap[a.tipo]||a.tipo||'Tipo?'} • ${a.date||'sem data'}`;
 }
 function savedAssessmentsWithData(){
  const list=(A().state.assessments||[]).filter(x=>(x.students||[]).length&&(x.questions||[]).length);
  const cur=A().state.assessment;
  if(cur&&cur.id&&(cur.students||[]).length&&(cur.questions||[]).length&&!list.some(x=>x.id===cur.id))list.unshift(cur);
  return list;
 }
 function groupedByClass(){
  const groups={};
  savedAssessmentsWithData().forEach(a=>{const turma=a.turma||'Turma não informada';(groups[turma]??=[]).push(a);});
  return groups;
 }
 function groupStats(list){
  const levels={'Elementar I':0,'Elementar II':0,'Básico':0,'Desejável':0};
  const descMap={}; let totalStudents=0, weighted=0, nAssess=0;
  (list||[]).forEach(a=>{
    const r=A().getResults?window.Diagnostico.compute(a):null; if(!r||!r.summary.nStudents)return;
    totalStudents+=r.summary.nStudents; weighted+=(r.summary.avg||0)*r.summary.nStudents; nAssess++;
    Object.entries(r.summary.levels||{}).forEach(([k,v])=>levels[k]=(levels[k]||0)+v);
    (r.descriptorStats||[]).forEach(d=>{const key=d.descritor||'Sem descritor';(descMap[key]??={descritor:key,total:0,correct:0,students:0,assessments:0});descMap[key].total+=d.total||0;descMap[key].correct+=d.correct||0;descMap[key].students+=d.students?.length||0;descMap[key].assessments++;});
  });
  const descriptorStats=Object.values(descMap).map(d=>({...d,percent:A().pct(d.correct,d.total)})).sort((a,b)=>a.percent-b.percent||b.students-a.students);
  return {avg:totalStudents?Math.round((weighted/totalStudents)*10)/10:0,totalStudents,nAssess,levels,descriptorStats,priority:(levels['Elementar I']||0)+(levels['Elementar II']||0)};
 }
 function coordBarRows(data){
  if(window.Diagnostico?.barRows)return window.Diagnostico.barRows(data,{compact:true});
  const max=Math.max(1,...data.map(x=>Number(x.value)||0));
  return '<div class="bar-chart bar-compact">'+data.map(x=>{const v=Number(x.value)||0;const w=Math.max(3,Math.round(v/max*100));return `<div class="bar-row"><span class="bar-label">${A().safe(x.label)}</span><div class="bar-track"><div class="bar-fill" style="width:${w}%"></div></div><span class="bar-value">${A().safe(x.suffix?v+x.suffix:v)}</span></div>`;}).join('')+'</div>';
 }
 function renderCoordClassPanel(){
  const sel=A().$('#coordClassSelect'), comp=A().$('#coordCompareClassSelect'), box=A().$('#coordClassComparison'); if(!sel||!comp||!box)return;
  const groups=groupedByClass(); const names=Object.keys(groups).sort((a,b)=>a.localeCompare(b,'pt-BR'));
  const oldSel=sel.value||'todas', oldComp=comp.value||'';
  sel.innerHTML='<option value="todas">Todas as turmas</option>'+names.map(t=>`<option value="${A().safe(t)}">${A().safe(t)}</option>`).join('');
  sel.value=(oldSel==='todas'||names.includes(oldSel))?oldSel:'todas';
  const compareOptions=names.filter(t=>t!==sel.value).map(t=>`<option value="${A().safe(t)}">${A().safe(t)}</option>`).join('');
  comp.innerHTML='<option value="">Selecione outra turma</option>'+compareOptions;
  comp.value=names.includes(oldComp)&&oldComp!==sel.value?oldComp:'';
  sel.onchange=()=>{comp.value=''; renderCoordClassPanel();}; comp.onchange=()=>renderCoordClassPanel();
  if(!names.length){box.innerHTML='<p class="hint">Nenhuma avaliação salva com dados. Salve avaliações por turma para habilitar análise da coordenação.</p>';return;}
  const selectedList=sel.value==='todas'?savedAssessmentsWithData():(groups[sel.value]||[]); const st=groupStats(selectedList);
  const allStats=names.map(t=>({turma:t,...groupStats(groups[t])})).sort((a,b)=>a.avg-b.avg);
  const avgBars=coordBarRows(allStats.map(x=>({label:x.turma,value:x.avg,suffix:'%'})));
  const priorityBars=coordBarRows(allStats.map(x=>({label:x.turma,value:x.priority})));
  const critical=st.descriptorStats.slice(0,8);
  let compHtml='';
  if(comp.value&&groups[comp.value]){
    const st2=groupStats(groups[comp.value]);
    const union=[...new Set([...critical.slice(0,5).map(d=>d.descritor),...st2.descriptorStats.slice(0,5).map(d=>d.descritor)])];
    const get=(arr,d)=>arr.find(x=>x.descritor===d);
    const rows=union.map(d=>{const a=get(st.descriptorStats,d), b=get(st2.descriptorStats,d);const pa=a?a.percent:null, pb=b?b.percent:null;const gap=(pa!=null&&pb!=null)?Math.round((pa-pb)*10)/10:null;return `<tr><td><b>${A().safe(d)}</b><br><small>${A().safe(window.Descritores?.get?.(A().state.assessment.discipline,d)?.texto||'Consultar matriz.')}</small></td><td>${pa==null?'-':pa+'%'}</td><td>${pb==null?'-':pb+'%'}</td><td>${gap==null?'-':gap+' p.p.'}</td></tr>`;}).join('');
    const diff=Math.round((st.avg-st2.avg)*10)/10;
    compHtml=`<div class="panel mini-panel"><h4>Comparação selecionada: ${A().safe(sel.value)} × ${A().safe(comp.value)}</h4><div class="cards small"><div class="card"><span>${A().safe(sel.value)}</span><b>${st.avg}%</b></div><div class="card"><span>${A().safe(comp.value)}</span><b>${st2.avg}%</b></div><div class="card"><span>Diferença</span><b>${diff} p.p.</b></div></div><h4>Descritores prioritários comparados</h4><div class="comparison-table"><table><thead><tr><th>Descritor</th><th>${A().safe(sel.value)}</th><th>${A().safe(comp.value)}</th><th>Diferença</th></tr></thead><tbody>${rows}</tbody></table></div><p class="hint"><b>Leitura:</b> priorize os descritores com menor percentual nas duas turmas; quando uma turma estiver muito abaixo da outra, promova troca de estratégias entre professores, análise dos distratores e reensino focalizado.</p></div>`;
  }
  const critList=critical.map(d=>`<li><b>${A().safe(d.descritor)}</b> — ${d.percent}% • ${d.students||0} estudante(s) com erro<br><small>${A().safe(window.Descritores?.get?.(A().state.assessment.discipline,d.descritor)?.texto||'Consultar matriz da disciplina.')}</small></li>`).join('')||'<li>Sem descritores suficientes.</li>';
  box.innerHTML=`<div class="chart-grid"><div class="panel chart-card"><h3>Média por turma</h3><p class="hint">Ranking das turmas salvas. Barras menores indicam turmas que exigem atenção.</p>${avgBars}</div><div class="panel chart-card"><h3>Alunos em Elementar I/II por turma</h3><p class="hint">Quantidade de estudantes que precisam de intervenção prioritária.</p>${priorityBars}</div></div><div class="panel"><h3>Turma analisada: ${A().safe(sel.value==='todas'?'Todas as turmas':sel.value)}</h3><div class="cards small"><div class="card"><span>Avaliações</span><b>${st.nAssess}</b></div><div class="card"><span>Alunos</span><b>${st.totalStudents}</b></div><div class="card"><span>Média</span><b>${st.avg}%</b></div><div class="card"><span>Elementar I/II</span><b>${st.priority}</b></div></div><h4>Descritores prioritários da seleção</h4><ol>${critList}</ol></div>${compHtml}`;
 }

 function renderCoord(){const box=A().$('#coordDashboard');if(!box)return;const r=A().getResults();const a=A().state.assessment;const last=A().state.snapshots?.slice(-1)[0];const crit=r.descriptorStats.slice(0,8);const prior=r.students.filter(s=>s.level==='Elementar I'||s.level==='Elementar II').slice(0,20);const bank=(window.BancoQuestoes?.allBank?.()||[]).filter(q=>q.discipline===a.discipline).length;const weakTurma=(A().state.snapshots||[]).reduce((acc,s)=>{const t=s.turma||'Turma não informada';(acc[t]??=[]).push(s.avg||0);return acc;},{});const turmaCritica=Object.entries(weakTurma).map(([t,arr])=>({t,avg:Math.round(arr.reduce((a,b)=>a+b,0)/arr.length*10)/10,n:arr.length})).sort((a,b)=>a.avg-b.avg)[0];
 const levelRows=Object.entries(r.summary.levels||{}).map(([k,v])=>`<li><b>${A().safe(k)}</b>: ${v} aluno(s)</li>`).join('');
 box.innerHTML=`<div class="cards"><div class="card"><span>Média</span><b>${r.summary.avg||0}</b></div><div class="card"><span>Elementar I/II</span><b>${r.summary.priority||0}</b></div><div class="card"><span>Descritores críticos</span><b>${r.descriptorStats.filter(d=>d.percent<40).length}</b></div><div class="card"><span>Histórico</span><b>${A().state.snapshots.length}</b></div><div class="card"><span>Questões no banco</span><b>${bank}</b></div></div><div class="panel"><h3>Leitura gestora da avaliação</h3><p><b>Avaliação atual:</b> ${A().safe(a.title||'Avaliação atual')} • ${A().safe(a.turma||'turma não informada')} • ${A().safe(a.discipline)}.</p><p><b>Situação atual:</b> média ${r.summary.avg||0} com ${r.summary.priority||0} aluno(s) em Elementar I/II.</p><p><b>Distribuição por níveis:</b></p><ul>${levelRows||'<li>Sem dados suficientes.</li>'}</ul><p><b>Turma crítica no histórico:</b> ${turmaCritica?A().safe(turmaCritica.t)+' • '+turmaCritica.avg+'% em '+turmaCritica.n+' registro(s)':'dados insuficientes.'}</p><p><b>Último registro histórico:</b> ${last?A().safe(last.name)+' • '+last.avg+'%':'nenhum registro salvo.'}</p></div>${actionPlan(r)}<div class="grid2"><div class="panel"><h3>Descritores críticos</h3><p class="hint">Priorize descritores abaixo de 40% ou com muitos alunos errando.</p><ol>${crit.map(d=>`<li><b>${A().safe(d.descritor)}</b> — ${d.percent}% • ${d.students.length} aluno(s)<br><small>${A().safe(window.Descritores?.get?.(a.discipline,d.descritor)?.texto||'Consultar matriz da disciplina.')}</small></li>`).join('')||'<li>Sem dados.</li>'}</ol></div><div class="panel"><h3>Alunos prioritários</h3><p class="hint">Estudantes em Elementar I/II devem ser acompanhados com plano curto e monitorável.</p><ul>${prior.map(s=>`<li>${A().safe(s.name)} — ${s.percent}% • ${s.level}</li>`).join('')||'<li>Nenhum aluno nesse grupo.</li>'}</ul></div></div><div class="panel"><h3>Ações que a coordenação pode realizar</h3><ul class="action-list"><li>Definir professores responsáveis por cada descritor crítico e acompanhar devolutiva em reunião pedagógica.</li><li>Reservar 4 semanas de recomposição: 1h de estudo orientado + 1h de resolução de exercícios por semana.</li><li>Solicitar evidências: lista aplicada, frequência, correção comentada e nova medição.</li><li>Comparar Português × Matemática na mesma turma para identificar desequilíbrios entre áreas.</li><li>Monitorar alunos que permanecem em Elementar I após a intervenção.</li></ul></div>`;renderHistory();renderComparison();renderCoordClassPanel();A().renderWizard?.();}
 function renderHistory(){const box=A().$('#history');if(!box)return;const snaps=A().state.snapshots||[];if(!snaps.length){box.innerHTML='<p class="hint">Nenhuma avaliação salva no histórico.</p>';return;} const max=Math.max(...snaps.map(s=>s.avg||0),100);box.innerHTML='<div class="history-chart">'+snaps.map(s=>`<div class="history-row"><b>${A().safe(s.name)}</b><div class="bar"><span style="width:${Math.max(3,(s.avg/max)*100)}%"></span></div><em>${s.avg}%</em><small>${A().safe(s.date)}</small></div>`).join('')+'</div>';}
 function bind(){document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const txt=build(b.dataset.report);A().state.currentReport=txt;A().$('#reportOutput').value=txt;A().save();});A().$('#copyReport')&&(A().$('#copyReport').onclick=()=>navigator.clipboard?.writeText(A().$('#reportOutput').value||''));A().$('#downloadReport')&&(A().$('#downloadReport').onclick=()=>A().download('relatorio-vetor.txt',A().$('#reportOutput').value||build('turma')));A().$('#exportReportPdf')&&(A().$('#exportReportPdf').onclick=()=>window.Exportacao?.printReport(A().$('#reportOutput').value||build('turma'),'Relatório VETOR'));A().$('#saveSnapshot')&&(A().$('#saveSnapshot').onclick=()=>{const r=A().getResults();if(!r.summary.nStudents)return alert('Importe uma avaliação antes de salvar histórico.');const name=A().norm(A().$('#snapshotName').value)||'Avaliação '+(A().state.snapshots.length+1);A().state.snapshots.push({id:A().uid(),name,date:new Date().toLocaleString('pt-BR'),avg:r.summary.avg,students:r.summary.nStudents,critical:r.descriptorStats.slice(0,5),discipline:A().state.assessment.discipline,turma:A().state.assessment.turma||'',tipo:A().state.assessment.tipo||'',levels:r.summary.levels||{}});A().save();renderCoord();});A().$('#clearSnapshots')&&(A().$('#clearSnapshots').onclick=()=>{if(confirm('Limpar histórico?')){A().state.snapshots=[];A().save();renderCoord();}});}
 window.Relatorios={turma,familia,conselho,coordenacao,individual,build,renderCoord,renderHistory,renderComparison,compareDisciplines};document.addEventListener('DOMContentLoaded',bind);
})();
